### ISSUE TITLE
Free Book Page (before 12/26)

### ISSUE THREAD

**Issue by juellez** [juellez/vdm#3]
This will replace current free book page & be for the new book. Get info from Nayana.

**Comment by juellez** [comment]
http://divination.com/freebook is the current URL.  no need to put any content around catching folks here looking for the iching book as it hasn't been used in a while. We'll catch both URLs ... not sure yet which one will be the canonical one.
- http://divination.com/freebook
- http://GreatDecisionsPerfectTiming.com/freebook

**Comment by paulo531** [comment]
the main thing is to change out the reference to the I Ching book to be replaced by "Great Decisions" PLUS changing the download link to go get the new book (of course, all of this needs to be timed for when we have a finished pdf of an edited version of GD book -- approx December 25)

**Comment by juellez** [comment]
done. went with GreatDecisionsPerfectTiming.com
